blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/KHET-1/md-reader-pro/discussions
    about: Ask questions, share ideas, and discuss features
  - name: 📖 Documentation
    url: https://github.com/KHET-1/md-reader-pro#readme
    about: Read the full documentation
  - name: 💡 Ideas Hub
    url: https://github.com/KHET-1/md-reader-pro/blob/main/IDEAS.md
    about: Browse and contribute ideas
  - name: 📋 Product Backlog
    url: https://github.com/KHET-1/md-reader-pro/blob/main/BACKLOG.md
    about: See what's planned for upcoming releases
